#设置账号密码
[admin]
auth=false
user="admin"
password="admin"
certificate="123456"

#设置web服务
[web]
name="N_m3u8DL-Web"
root_path="wwwroot"
run_url="http://*:5550"

#设置存储位置
[storage]
path="./storage"

#下载
[download]
http_request_timeout=60
use_system_proxy=true
task_queue_size=16
task_workers=5
task_download_thread=5
task_load_timeout=30
